#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OWNER="${GITHUB_OWNER:-tara32473}"
repos=(budget-manager portfolio-website quiz-app task-tracker weather-dashboard)
BADGE_START='<!-- BADGES:START -->'
BADGE_END='<!-- BADGES:END -->'

TMP="$(mktemp -t readme.XXXXXX)" || exit 1
TMP_BADGES="${TMP}.badges"
trap 'rm -f "$TMP" "$TMP_BADGES"' EXIT

# Build badge block
{
  echo "$BADGE_START"
  echo "<!-- Generated by scripts/add-badges.sh -->"
  echo
  for r in "${repos[@]}"; do
    echo "<!-- badges for ${r} -->"
    echo "[![CI](https://github.com/${OWNER}/${r}/actions/workflows/ci.yml/badge.svg)](https://github.com/${OWNER}/${r}/actions)"
    echo "[![Coverage](https://codecov.io/gh/${OWNER}/${r}/branch/main/graph/badge.svg)](https://codecov.io/gh/${OWNER}/${r})"
    echo
  done
  echo "$BADGE_END"
} > "$TMP_BADGES"

# Remove existing badge block (if any) and write the rest to TMP
awk -v start="$BADGE_START" -v end="$BADGE_END" -v bfile="$TMP_BADGES" '
  BEGIN {
    while ((getline line < bfile) > 0) badges = badges line "\n"
    printed = 0
    inblock = 0
  }
  {
    if ($0 ~ start) {
      # replace old block with generated badges once
      if (!printed) { printf "%s", badges; printed = 1 }
      inblock = 1
      next
    }
    if ($0 ~ end) { inblock = 0; next }
    if (!inblock) print
  }
' README.md > "$TMP"

# If there was no start marker, prepend badges at the top
if ! grep -qF "$BADGE_START" README.md; then
  cat "$TMP_BADGES" README.md > "$TMP"
fi

echo
echo "Preview diff (README.md -> proposed README):"
git --no-pager diff --no-index -- README.md "$TMP" || true
echo

read -r -p "Apply these changes to README.md and commit? [y/N] " resp
case "${resp,,}" in
  y|yes)
    if cmp -s README.md "$TMP"; then
      echo "README would not change — no commit created."
      exit 0
    fi

    cp README.md README.md.bak."$(date +%Y%m%dT%H%M%S)"
    mv "$TMP" README.md
    git add README.md
    git commit -m "chore(readme): insert canonical badges block (generated)"
    echo "README updated and committed."
    ;;
  *)
    echo "No changes applied. Proposed file is at: $TMP"
    exit 0
    ;;
esac
