#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OWNER="${GITHUB_OWNER:-tara32473}"
repos=(budget-manager portfolio-website quiz-app task-tracker weather-dashboard)
BADGE_START='<!-- BADGES:START -->'
BADGE_END='<!-- BADGES:END -->'
TMP="$(mktemp -t readme.XXXXXX)" || exit 1
trap 'rm -f "$TMP"' EXIT

# Build badge block
{
  echo "$BADGE_START"
  echo "<!-- Generated by scripts/add-badges.sh -->"
  echo
  for r in "${repos[@]}"; do
    echo "<!-- badges for ${r} -->"
    echo "[![CI](https://github.com/${OWNER}/${r}/actions/workflows/ci.yml/badge.svg)](https://github.com/${OWNER}/${r}/actions)"
    echo "[![Coverage](https://codecov.io/gh/${OWNER}/${r}/branch/main/graph/badge.svg)](https://codecov.io/gh/${OWNER}/${r})"
    echo
  done
  echo "$BADGE_END"
} > "$TMP.badges"

# Remove existing badge block and create new README (keep the rest)
awk -v start="$BADGE_START" -v end="$BADGE_END" -v bfile="$TMP.badges" '
  BEGIN {
    while ((getline line < bfile) > 0) badges = badges line "\n"
    inblock = 0
  }
  {
    if ($0 ~ start) { inblock = 1; if (!printed) { print; printf "%s", badges; printed=1 } ; next }
    if ($0 ~ end) { inblock = 0; next }
    if (!inblock) print
  }
' README.md > "$TMP"

# If no start marker existed, prepend badges
if ! grep -qF "$BADGE_START" README.md; then
  cat "$TMP.badges" README.md > "$TMP"
fi

echo
echo "Preview diff (README.md -> proposed README):"
git --no-pager diff --no-index -- README.md "$TMP" || true
echo

read -r -p "Apply these changes to README.md and commit? [y/N] " resp
case "${resp,,}" in
  y|yes)
    cp README.md README.md.bak."$(date +%Y%m%dT%H%M%S)"
    mv "$TMP" README.md
    git add README.md
    git commit -m "chore(readme): insert canonical badges block (generated)"
    echo "README updated and committed."
    ;;
  *)
    echo "No changes applied. Proposed file is at: $TMP"
    exit 0
    ;;
esac
